macro(enable_ccache)
    find_program(CCACHE "ccache")
    if(CCACHE)
        message(STATUS "use ccache")
        set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE})
        set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE})
    else()
        message(WARNING "ccache not found")
    endif(CCACHE)
endmacro()
